build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install -r docs/requirements.txt # or install your package/docs requirements
    post_build:
      # 1. Build the HTML documentation using Sphinx
      - sphinx-build -b html safe_vamd/docs/source $READTHEDOCS_OUTPUT/html